format_version: v1.0
type: UniqueComponent
attributes: {id: drvPic32mEthmac}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DRV_INTMAC_PHY_TYPE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: drvPic32mEthmac, value: LAN8740}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: libdrvPic32mEthmac}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: AmazonHWInterface}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NETCONFIG_MAC_Dependency}
- type: ElementPosition
  attributes: {x: '309', y: '379', id: drvPic32mEthmac}
